### PR TITLE
script: Add `--abort-on-error` flag

### PR DESCRIPTION
**Pull request by accuminium**
This flag causes compilation/analysis scripts to abort on errors that can be caught with Tcl's `catch`.

### CODE REVIEW

**Comment by accuminium** [comment]
I think it is useful to have an option that lets analysis/compilation abort if errors are encountered.

@fabianschuiki: What do you think? Should this even be the default behavior and should we instead have an `--ignore-errors` switch?

**Comment by fabianschuiki** [comment]
Any thoughts on how we should proceed with this?

**Comment by accuminium** [comment]
I forgot that we never merged this, sorry. I still think it's very useful to abort on first error when possible. I rebased on current `master` and enabled aborting by default, as you suggested.

**Comment by fabianschuiki** [comment]
Perfect thanks! I quickly ran `cargo fmt` over it to make CI pass. Then I'll merge and release.

**Pull request merged**
